ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQXofGq1J+U1Sc03ohNMYGHzANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwMzE4MDY1NjA0WhcNMzYw
  MzE1MDY1NjA0WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC/vcKDudfz1bQVNfmAiH5AJHiD/PJ8ogfq
  ChVAQug1ldOoF7no5ndjTrbo1YtbPe4nMV+8XQLuheLx5QBsb/z9UT1quybcSYlF
  HYSy2pmgUm0W9MqwniT2oXSlhe87PNc5gwRufDKqS4y0ygCkDDP5eg9GIDOYOGdK
  JV2qXLPeXFFzyy7PrjwFT8abXOsqjDvOLPaLPjw7vz38mF88BT71HwagOAuCP/hS
  hNRAARZyRpFo9viTmRGWMu8UC/FA/AiiXGJHeSa4zMDlFUfV3opT42WSM4cWM7/9
  3FBC5r1JlRcebaSBTj2RPk9nbfTbYSzIbNyQWNk8xqW2uaSitFKVAgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTsL26gEen9uqdeJzNnpvU6utq7
  XDAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAM7jCDhiH571VsLzu+Bd8ccEROuwRLH+4RBjM49tlTISx
  ZcyhiMfc+/bJ78nxbiDQMgHFLhE/1Ia31iSYUYiCLWEPBUXaBgbQs/Xw8DWdMkHa
  nFqpngngeyBPESi0uH4LnI66RTMZxvLnWev64LdX5p5S9NG+Z6W0T4qmjafauE+7
  +TdyuDvEQTn4wQkvUjcrleJhm2rhL+FDSYEDtW+KSfIg8rSvS/I2L7dln4p/VGTv
  D7v8qaEm5Zel4JzaWD+1Mg0IfHREXp7z9KNcZIB6rzPisyrhH8kQxciYFgks+0SZ
  0x4SHFBhSb3KarFfSDFX7v+RPwtmRzw4do7ClqmTVQ==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPTCCAiWgAwIBAgIQLL6mG7KSbZGfOMLnLrdMJTANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwMzE4MTAxODI2WhcNMjcw
  MzE4MTAxODI2WjAnMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDjAMBgNVBAMTBWFk
  bWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7YDKxGJ5IQxKMzcp
  j2o6u51exNxi4ZjVqYYSpgZSQc5wTxiL2yn1beLTyBsjoNlhsTzeGs+hlWLrN6HO
  aIfQogxy4KBf1BzedpfP1yFW7g6RjDYPyWsAhte6jXoy78G/zqCuDGdF0K9E7FM3
  ODtsmidHsGCCPlfqSAqSyKu7y4NZUNG0/NKvNaCQ1ElzAfBU3QL1MBQtbe+IcDFY
  G+yyMOlblcUngSkybP7k1hA6arSfRorJgnOIxEcwBjFNeri8lsjDCZr4DAazoiJj
  7Nkr0DdegCvv2LtCwbNcASoe+R7ePOnuQntsJFztjr7VbC62EWZZeRwwY0pMfGqE
  qqWxyQIDAQABo3IwcDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
  AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAU7C9uoBHp/bqn
  XiczZ6b1Orrau1wwEAYDVR0RBAkwB4IFYWRtaW4wDQYJKoZIhvcNAQELBQADggEB
  ABee4BGemkkGg92X5HCqtfpLUCtmoMigPYCemtHE8PAzM5IvASHsEYmcBGyHN/mL
  6cf+Da/471sosUeuBxmIo3wIGrIps8elABXxRA/8pxJLkC/ZsJBnyJlYtQy0xFvZ
  uCeSh6VAwRd7KCVKs2aUsuwmWRcRVPofsZlSWuMtdZVKMxVpr4vG2d+EMQyi0r2/
  bNU6Cj0RVZAn2VByqe7Djpy6w2GvAYTe5/jKzY86oAn3E6jpuAfDiHzpTjILy0n0
  gwxGlnh8TCbHNNznYBfCrkCxxSl+VnjdanVXEP7y36SKyqLqNF3uJnS5QWGQffvv
  9RHknbFzroCh7W6Y4WVXfnQ=
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEA7YDKxGJ5IQxKMzcpj2o6u51exNxi4ZjVqYYSpgZSQc5wTxiL
  2yn1beLTyBsjoNlhsTzeGs+hlWLrN6HOaIfQogxy4KBf1BzedpfP1yFW7g6RjDYP
  yWsAhte6jXoy78G/zqCuDGdF0K9E7FM3ODtsmidHsGCCPlfqSAqSyKu7y4NZUNG0
  /NKvNaCQ1ElzAfBU3QL1MBQtbe+IcDFYG+yyMOlblcUngSkybP7k1hA6arSfRorJ
  gnOIxEcwBjFNeri8lsjDCZr4DAazoiJj7Nkr0DdegCvv2LtCwbNcASoe+R7ePOnu
  QntsJFztjr7VbC62EWZZeRwwY0pMfGqEqqWxyQIDAQABAoIBADKm6heyDLVQoq6D
  kDiG5lnG+UQw4GHOr5rE/kssQ/TG60rjKEiojTBPVO1zZEjUs7ISEihTqdlrTFEE
  EDpY5NT6pLFlYqqhMYzHWcs+0ARbVQ07JmjFiko3zhCIRD6/6oFN4XDBwbD9AE0K
  fldezQ2fXPmvy3cyVsPghWeIwLdpNb/M9pVIlxd3xbAaM8sLtOKME7DGkJWf//Hr
  jrp6s/IFePiZY9kwmrDZgjpwg6zJiSxD/6Cwcvfz/qgLsnw1c1kC4O2+M+ErbBSP
  iKwQngPi15zWve1Ua/adYKkvwF1l5Yf7MUl2vWHGdctAy3E00DWOz4K7r/ZwomQa
  td3FCoECgYEA9Dm7PwHM1XmpEVEgFoDV7qbyzLw8WLmO/5OjodLa/eT9Xj6TMQqZ
  xSL4jqFY1QEabTV45c7mqhktuR+MqMbapG5reWoWRcmBIOTxgve41LJ/qTsop7yI
  6/e5D/7OuMZst0oNCQR2Ls1g4uOuPjh4Zw/KxUTLn0WwTHzCZFuhnnECgYEA+PQX
  bLCe8gnLCvPvGcZ5Z5SJZ3+Kzms2i1qcrrhnLSY4Yo1r8UA1f51uZ90BuDZ18wb+
  OGGMi9+hPyWbPNXc5MX8b0mPU49xT7QYVM/1UKQx4jjvq3QpOw7k02OpTfam46Pt
  Q9AkujBuwu4zI8tJ/+luNZyQjK5NxdBrHeaGpNkCgYEAt6tfNaBd8sHfM0XGkwXr
  XeKyQOTjoXpTn8Ph0MapqT34ilMXEU++mzKUqXeQPgjpXe5T8MhsUspCx7GBcEC0
  l+ru6s2s2GkVsq5bLzqsB1ICjjwOdC9m7cdMp0njH7Uid6m6KejwFHyie5/tH6AK
  dL+8qCT32d1oG+3Lp/v9jRECgYAsHDO6UmEXSZzsR+RpkL0aGTtvVy3k/SIg9uEk
  JBBD862x6JTjnhjcj6xsQsB3P08OzIJmwwIAFpOfeK5UzR/ieSINJd97UsMk+CgH
  fwFcVHtyNdxhaKeVi0IIInRxF+7iDr2PcmXPh51YdJQjF3X5HgclAKSsCIZHMnKI
  Tbw1oQKBgFcT8x8YbdjXGw2/aG9EYRwmW8EtmmMQCuC8vNav2WJm02qw3Y6JRTiF
  mBgO6Y0/GrOwg8t9SA66B/mrGNUxfF3Au0VUIeLz4IyKnczHlPh/5l4jB0H/CF7W
  MAdeiLPe7rcbErX52KmnKst1VHo8zc/sjNp2yVJvPHzlYcEQvfGU
  -----END RSA PRIVATE KEY-----
api_connection_string: 127.0.0.1:8001
name: admin
